---
- name: Add Docker repo
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root 
    group: root 
    mode: 0644
  with_items: centos_files
  
  tags: [docker]

- name: Install Docker
  yum:
    name: docker-engine
    enablerepo: docker
    state: latest
  
  tags: [docker]


- name: CentOS service is running
  service:
    name: docker
    state: running
  
  tags: [docker]

- name: python-pip is present
  yum:
     name: python-pip
     state: present
  become: yes
  tags: [docker]