version: '2'

services:

  consul:
    image: progrium/consul
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"
    command: -server -bootstrap -advertise 192.168.99.100  -ui-dir /ui

  registrator:
    depends_on:
      - consul
    image: gliderlabs/registrator:latest
    command: -ip=192.168.99.100 consul://consul:8500
    links:
      - consul
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"

  zookeeper:
    image: wurstmeister/zookeeper
    ports: 
      - "2181"
 
  kafka:
    depends_on: 
      - zookeeper
      - registrator
    build: 
      context: .
    ports:
      - "9092"
    links: 
      - zookeeper:zk
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
